import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../assets/styles/globals.scss";

const firstFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={firstFont.className}>{children}</body>
    </html>
  );
}
