import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../assets/styles/globals.scss";
import styles from "./layout.module.scss";

import Sidebar from "@/components/sidebar/Sidebar";

const firstFont = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={firstFont.className}>
        <div className={styles.layout}>
          <div className={styles.sidebar}>
            <Sidebar />
          </div>
          <div className={styles.content}>{children}</div>
        </div>
      </body>
    </html>
  );
}
